language: android

jdk:
  oraclejdk8

android:
  components:
    - android-23
    - build-tools-23.0.3
    - platform-tools
    - tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

install:
  ./gradlew clean assembleDebug test
